apache:
  restart: always
  image: fusengine/apache-php
  ports:
      - "80:80"
  volumes: # creation de volume entre les machines DossierLocal{mac}:DossierConteneur{docker}
      - /Users/brunoazoulay/Docker/lab/local.dev:/app/web
      - /Users/brunoazoulay/Docker/lab/config/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
      - /Users/brunoazoulay/Docker/lab/config/sites:/etc/apache2/sites-enabled
  environment:
      - ALLOW_OVERRIDE=true
  links: #creation de lien entre conteneur
      - bdd:bdd
      - maildev:mail

# Base de donnée MariaDB
bdd:
  restart: always
  image: fusengine/mariadb-osx
  ports:
    - "36:3306"
  volumes:
    - /Users/brunoazoulay/Docker/BDD/data:/var/lib/mysql
    - /Users/brunoazoulay/Docker/BDD/mysql:/etc/mysql

# Composer
composer:
  restart: always
  image: fusengine/composer
  volumes_from:
    - apache

# Serveur MailDev
maildev:
  restart: always
  image: djfarrelly/maildev
  ports:
    - "81:80" # le port 1080 va communiquwe avec le port 80 de notre machine
